#wps密码配置
wps:
  domain: http://59.255.109.59/office/

# MinIo文件服务器
minio:
  endpoint: http://59.255.109.59:9000
#  映射到外网/政务网服务地址
  net-endpoint: http://59.255.109.59:9000
  accessKey: AKIARI2NQQXV66BZE4OO
  secretKey: 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
  bucketName: filewps

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://59.255.109.57:5432/wps
    username: postgres
    password: zhzx@admin
  servlet:
    multipart:
      max-file-size: 50MB  #单个数据大小
      max-request-size: 100MB #总数据大小