server:
  port: 8123

#wps密码配置
wps:
  domain: https://wwo.wps.cn/office/
  #appid: 8c5f9f36750d418d92dd8d031ad5ac73
  #appsecret: 3dae357b988d4c82bc413ba9bbb1668e

# MinIo文件服务器
minio:
  endpoint: http://59.255.109.59:9000
#  映射到外网/政务网服务地址
  net-endpoint: http://59.255.109.59:9000
  #accessKey: minioadmin
  #secretKey: minioadmin
  accessKey: AKIARI2NQQXV66BZE4OO
  secretKey: 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
  bucketName: filewps

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://59.255.109.57:5432/wps
    username: postgres
    password: zhzx@admin
    #password: scyj123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
