#wps密码配置
wps:
  domain: http://59.255.109.59/office/

# MinIo文件服务器
minio:
  endpoint: http://59.255.109.59:9001
#  映射到外网/政务网服务地址
  net-endpoint: http://59.255.109.59:9001
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucketName: filewps

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://59.255.109.57:5432/wps
    username: postgres
    password: zhzx@admin
