server:
  port: 8080
#wps密码配置
wps:
  domain: https://wwo.wps.cn/office/
  signature: true
  appid: 8c5f9f36750d418d92dd8d031ad5ac73
  appsecret: 3dae357b988d4c82bc413ba9bbb1668e

# MinIo文件服务器
minio:
  endpoint: http://192.168.30.127:9000
  #  映射到外网/政务网服务地址
  net-endpoint: http://117.139.13.147:9000
  # http://yy.ngrok2.xiaomiqiu.cn
#  accessKey: AKIAIOSFODNN7EXAMPLE
#  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: wps

spring:
  datasource:
    dynamic:
      strict: true
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.30.127:5432/wps
          username: postgres
          password: scyj123
        zb:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.30.127:5432/dcjt-zbxt-wps-preview
          username: postgres
          password: scyj123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 50MB  #单个数据大小
      max-request-size: 100MB #总数据大小